name: Publish

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths-ignore:
      - '.github/**'

jobs:
  publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@main
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@main
        with:
          node-version: ${{ matrix.node-version }}
      - name: Check and Publish to GitHub Package Registry
        run: |
          yarn install
          npm publish --access public --tag alpha
        env:
          NPM_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
